[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.f_cpu = 160000000L
lib_extra_dirs = .
lib_deps = 
    logic_analyzer
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D CORE_DEBUG_LEVEL=0
    -D CONFIG_LOG_DEFAULT_LEVEL=0
    -D CONFIG_ANALYZER_USE_SUMP=1
    -D CONFIG_ANALYZER_USE_USB_SERIAL_JTAG=1
    -D CONFIG_ANALYZER_UART_PORT_NUMBER=0
    -D CONFIG_ANALYZER_UART_PORT_BAUD_RATE=115200
    -D CONFIG_ANALYZER_UART_PORT_TX_PIN=21
    -D CONFIG_ANALYZER_UART_PORT_RX_PIN=20
    -D CONFIG_ANALYZER_USE_PORT_ASSIGN=1
    -D CONFIG_ANALYZER_CHAN_0=5
    -D CONFIG_ANALYZER_CHAN_1=6
    -D CONFIG_ANALYZER_CHAN_2=1
    -D CONFIG_ANALYZER_CHAN_3=-1
    -D CONFIG_ANALYZER_CHAN_4=-1
    -D CONFIG_ANALYZER_CHAN_5=-1
    -D CONFIG_ANALYZER_CHAN_6=-1
    -D CONFIG_ANALYZER_CHAN_7=-1
    -D CONFIG_ANALYZER_CHAN_8=-1
    -D CONFIG_ANALYZER_CHAN_9=-1
    -D CONFIG_ANALYZER_CHAN_10=-1
    -D CONFIG_ANALYZER_CHAN_11=-1
    -D CONFIG_ANALYZER_CHAN_12=-1
    -D CONFIG_ANALYZER_CHAN_13=-1
    -D CONFIG_ANALYZER_CHAN_14=-1
    -D CONFIG_ANALYZER_CHAN_15=-1
    -D CONFIG_ANALYZER_TRIG_PIN=-1
    -D CONFIG_ANALYZER_TRIG_EDGE=1
    -D CONFIG_ANALYZER_SAMPLES_COUNT=1000
    -D CONFIG_ANALYZER_SAMPLE_RATE=1000000
    -D CONFIG_ANALYZER_TIMEOUT=20000
    -D CONFIG_ANALYZER_CHANNELS=8
    -D CONFIG_ANALYZER_PSRAM=0
    -I logic_analyzer/logic_analyzer_hal/include
    -I logic_analyzer/logic_analyzer_hal/private_include
    -I logic_analyzer/logic_analyzer_sump/include
    -I logic_analyzer/logic_analyzer_sump/private_include
    -I logic_analyzer/logic_analyzer_hal/esp32c3/private_include
